removing std::move
since Mesh appears to just hold a few pointers, there is no real speed gain trying to use std::move in this case.  It should in fact be safe to make copies of this struct, its internal pointers are still valid.  If logically the design requires a single pointer like source, then use a pointer. 
```
/usr/include/c++/13/bits/stl_construct.h:96:17: error: use of deleted function ‘Mesh::Mesh(const Mesh&)’
   96 |     -> decltype(::new((void*)0) _Tp(std::declval<_Args>()...))
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/rap/Net-Ghost-SE/Source/Model.h:10:
/home/rap/Net-Ghost-SE/Source/Mesh.h:14:7: note: ‘Mesh::Mesh(const Mesh&)’ is implicitly deleted because the default definition would be ill-formed:
   14 | class Mesh {
      |       ^~~~
/home/rap/Net-Ghost-SE/Source/Mesh.h:14:7: error: use of deleted function ‘constexpr VAO::VAO(const VAO&)’
In file included from /home/rap/Net-Ghost-SE/Source/Mesh.h:7:
/home/rap/Net-Ghost-SE/Source/VAO.h:10:7: note: ‘constexpr VAO::VAO(const VAO&)’ is implicitly declared as deleted because ‘VAO’ declares a move constructor or move assignment operator
   10 | class VAO
      |       ^~~
/home/rap/Net-Ghost-SE/Source/Mesh.h:14:7: error: use of deleted function ‘constexpr VBO::VBO(const VBO&)’
   14 | class Mesh {
      |       ^~~~
In file included from /home/rap/Net-Ghost-SE/Source/VAO.h:8:
/home/rap/Net-Ghost-SE/Source/VBO.h:19:7: note: ‘constexpr VBO::VBO(const VBO&)’ is implicitly declared as deleted because ‘VBO’ declares a move constructor or move assignment operator
   19 | class VBO
      |       ^~~
/home/rap/Net-Ghost-SE/Source/Mesh.h:14:7: error: use of deleted function ‘constexpr EBO::EBO(const EBO&)’
   14 | class Mesh {
      |       ^~~~
In file included from /home/rap/Net-Ghost-SE/Source/Mesh.h:8:
/home/rap/Net-Ghost-SE/Source/EBO.h:10:7: note: ‘constexpr EBO::EBO(const EBO&)’ is implicitly declared as deleted because ‘EBO’ declares a move constructor or move assignment operator
   10 | class EBO
      |       ^~~
In file included from /usr/include/c++/13/vector:65,
                 from /home/rap/Net-Ghost-SE/Source/Daemon.h:5,
                 from /home/rap/Net-Ghost-SE/Source/Scene.h:20:
/usr/include/c++/13/bits/stl_uninitialized.h: In instantiation of ‘constexpr bool std::__check_constructible() [with _ValueType = Mesh; _Tp = Mesh&&]’:
/usr/include/c++/13/bits/stl_uninitialized.h:182:4:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = move_iterator<Mesh*>; _ForwardIterator = Mesh*]’
/usr/include/c++/13/bits/stl_uninitialized.h:373:37:   required from ‘constexpr _ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, allocator<_Tp>&) [with _InputIterator = move_iterator<Mesh*>; _ForwardIterator = Mesh*; _Tp = Mesh]’
/usr/include/c++/13/bits/stl_uninitialized.h:399:2:   required from ‘constexpr _ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = Mesh*; _ForwardIterator = Mesh*; _Allocator = allocator<Mesh>]’
/usr/include/c++/13/bits/vector.tcc:493:3:   required from ‘constexpr void std::vector<_Tp, _Alloc>::_M_realloc_insert(iterator, _Args&& ...) [with _Args = {const Mesh&}; _Tp = Mesh; _Alloc = std::allocator<Mesh>; iterator = std::vector<Mesh>::iterator]’
/usr/include/c++/13/bits/stl_vector.h:1289:21:   required from ‘constexpr void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = Mesh; _Alloc = std::allocator<Mesh>; value_type = Mesh]’
/tmp/__main__.cpp:156:23:   required from here
/usr/include/c++/13/bits/stl_uninitialized.h:90:56: error: static assertion failed: result type must be constructible from input type
   90 |       static_assert(is_constructible<_ValueType, _Tp>::value,
      |                                                        ^~~~~
/usr/include/c++/13/bits/stl_uninitialized.h:90:56: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
/usr/include/c++/13/bits/stl_construct.h: In instantiation of ‘constexpr void std::_Construct(_Tp*, _Args&& ...) [with _Tp = Mesh; _Args = {Mesh}]’:
/usr/include/c++/13/bits/stl_uninitialized.h:120:21:   required from ‘constexpr _ForwardIterator std::__do_uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = move_iterator<Mesh*>; _ForwardIterator = Mesh*]’
/usr/include/c++/13/bits/stl_uninitialized.h:371:30:   required from ‘constexpr _ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, allocator<_Tp>&) [with _InputIterator = move_iterator<Mesh*>; _ForwardIterator = Mesh*; _Tp = Mesh]’
/usr/include/c++/13/bits/stl_uninitialized.h:399:2:   required from ‘constexpr _ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = Mesh*; _ForwardIterator = Mesh*; _Allocator = allocator<Mesh>]’
/usr/include/c++/13/bits/vector.tcc:493:3:   required from ‘constexpr void std::vector<_Tp, _Alloc>::_M_realloc_insert(iterator, _Args&& ...) [with _Args = {const Mesh&}; _Tp = Mesh; _Alloc = std::allocator<Mesh>; iterator = std::vector<Mesh>::iterator]’
/usr/include/c++/13/bits/stl_vector.h:1289:21:   required from ‘constexpr void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = Mesh; _Alloc = std::allocator<Mesh>; value_type = Mesh]’
/tmp/__main__.cpp:156:23:   required from here
/usr/include/c++/13/bits/stl_construct.h:115:28: error: no matching function for call to ‘construct_at(Mesh*&, Mesh)’
  115 |           std::construct_at(__p, std::forward<_Args>(__args)...);
      |           ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/13/bits/stl_construct.h:94:5: note: candidate: ‘template<class _Tp, class ... _Args> constexpr decltype (::new(void*(0)) _Tp) std::construct_at(_Tp*, _Args&& ...)’
   94 |     construct_at(_Tp* __location, _Args&&... __args)
      |     ^~~~~~~~~~~~
/usr/include/c++/13/bits/stl_construct.h:94:5: note:   template argument deduction/substitution failed:
/usr/include/c++/13/bits/stl_construct.h: In substitution of ‘template<class _Tp, class ... _Args> constexpr decltype (::new(void*(0)) _Tp) std::construct_at(_Tp*, _Args&& ...) [with _Tp = Mesh; _Args = {Mesh}]’:
/usr/include/c++/13/bits/stl_construct.h:115:21:   required from ‘constexpr void std::_Construct(_Tp*, _Args&& ...) [with _Tp = Mesh; _Args = {Mesh}]’
/usr/include/c++/13/bits/stl_uninitialized.h:120:21:   required from ‘constexpr _ForwardIterator std::__do_uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = move_iterator<Mesh*>; _ForwardIterator = Mesh*]’
/usr/include/c++/13/bits/stl_uninitialized.h:371:30:   required from ‘constexpr _ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, allocator<_Tp>&) [with _InputIterator = move_iterator<Mesh*>; _ForwardIterator = Mesh*; _Tp = Mesh]’
/usr/include/c++/13/bits/stl_uninitialized.h:399:2:   required from ‘constexpr _ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = Mesh*; _ForwardIterator = Mesh*; _Allocator = allocator<Mesh>]’
/usr/include/c++/13/bits/vector.tcc:493:3:   required from ‘constexpr void std::vector<_Tp, _Alloc>::_M_realloc_insert(iterator, _Args&& ...) [with _Args = {const Mesh&}; _Tp = Mesh; _Alloc = std::allocator<Mesh>; iterator = std::vector<Mesh>::iterator]’
/usr/include/c++/13/bits/stl_vector.h:1289:21:   required from ‘constexpr void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = Mesh; _Alloc = std::allocator<Mesh>; value_type = Mesh]’
/tmp/__main__.cpp:156:23:   required from here
/usr/include/c++/13/bits/stl_construct.h:96:17: error: use of deleted function ‘Mesh::Mesh(const Mesh&)’
   96 |     -> decltype(::new((void*)0) _Tp(std::declval<_Args>()...))
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/13/bits/stl_construct.h: In instantiation of ‘constexpr void std::_Construct(_Tp*, _Args&& ...) [with _Tp = Mesh; _Args = {Mesh}]’:
/usr/include/c++/13/bits/stl_uninitialized.h:120:21:   required from ‘constexpr _ForwardIterator std::__do_uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = move_iterator<Mesh*>; _ForwardIterator = Mesh*]’
/usr/include/c++/13/bits/stl_uninitialized.h:371:30:   required from ‘constexpr _ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, allocator<_Tp>&) [with _InputIterator = move_iterator<Mesh*>; _ForwardIterator = Mesh*; _Tp = Mesh]’
/usr/include/c++/13/bits/stl_uninitialized.h:399:2:   required from ‘constexpr _ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = Mesh*; _ForwardIterator = Mesh*; _Allocator = allocator<Mesh>]’
/usr/include/c++/13/bits/vector.tcc:493:3:   required from ‘constexpr void std::vector<_Tp, _Alloc>::_M_realloc_insert(iterator, _Args&& ...) [with _Args = {const Mesh&}; _Tp = Mesh; _Alloc = std::allocator<Mesh>; iterator = std::vector<Mesh>::iterator]’
/usr/include/c++/13/bits/stl_vector.h:1289:21:   required from ‘constexpr void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = Mesh; _Alloc = std::allocator<Mesh>; value_type = Mesh]’
/tmp/__main__.cpp:156:23:   required from here
/usr/include/c++/13/bits/stl_construct.h:119:7: error: use of deleted function ‘Mesh::Mesh(const Mesh&)’
  119 |       ::new((void*)__p) _Tp(std::forward<_Args>(__args)...);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```